import EcosystemCard from "../components/EcosystemCard";
import EcosystemGrid from "../components/EcosystemGrid";

export const metadata = {
    title: "Algebra Labs | Ecosystem | DEXes",
    description: "Algebra Labs ecosystem DEXes page",
};


const dexs = [
    { logo: '/logos/blackhole.jpg', name: 'Blackhole', description: 'The Arbitrum native DEX. Custom-built liquidity infrastructure to support builders & generate real yield' },
    { logo: '/logos/thena.svg', name: 'THENA', description: 'THE ULTIMATE decentralized\nexchange with ve(3,3), V4 plugins & more' },
    { logo: '/logos/supernova.svg', name: 'Supernova', description: 'Next-gen ve(3,3) DEX on Ethereum powered by Algebra Integral' },
    { logo: '/logos/camelot.svg', name: 'Camelot', description: 'The Arbitrum native DEX. Custom-\nbuilt liquidity infrastructure to\nsupport builders & generate real\nyield' },
    { logo: '/logos/main.png', name: 'Main', description: 'The first AI-governed DEX for Agentic Finance: modular & AI-native' },
    { logo: '/logos/hydrex.jpg', name: 'Hydrex', description: "Base's Frictionless Liquidity Hub:\nOmni-Liquidity MetaDEX powered by Integral" },
    { logo: '/logos/stellaswap.svg', name: 'StellaSwap', description: 'A one-stop DEX: trading, LPing & liquid staking on Polkadot & Moonbeam' },
    { logo: '/logos/cypher.jpg', name: 'Cypher', description: 'Ethereum Capital Markets. Native L1 market infrastructure powered by Integral' },
    { logo: '/logos/nest.svg', name: 'Nest', description: 'The MetaDEX built for Hyperliquid: smart pools & efficient swaps with ve(3,3) rewards, CLAMM & more' },
    { logo: '/logos/spark.svg', name: 'SparkDex', description: 'First AI-driven DeFi ecosystem on Flare Network' },
    { logo: '/logos/rooster.jpg', name: 'Rooster', description: 'Official RWA liquidity hub on Plume Network, pioneering the future of RWAFi' },
    { logo: '/logos/henesys.svg', name: 'Henesys', description: 'Better CLAMM + V4 pools with permissioned access on Henesys L1 by MapleStory' },
    { logo: '/logos/swapx.svg', name: 'SwapX', description: 'Revolutionary Modular Architecture: CLAMM V4 DEX on Sonic, powered by Integral' },
    { logo: '/logos/kittenswap.jpg', name: 'KittenSwap', description: 'A community owned DEX on HyperEVM with ve(3,3) mechanics powered by Algebra' },
    { logo: '/logos/molten.jpg', name: 'Molten', description: 'Core’s native liquidity engine for Bitcoin DeFi. BTC-backed swaps, yield vaults & deep liquidity' },
    { logo: '/logos/satsuma.svg', name: 'Satsuma', description: 'The Native Liquidity Layer on Citrea powered by Algebra Integral' },
    { logo: '/logos/swapr.svg', name: 'Swapr', description: 'DeFi power tool: swap, farm & bridge without worrying about privacy' },
    { logo: '/logos/voltage.svg', name: 'Voltage', description: 'All-in-one DeFi hub on Fuse network. Trade, earn and govern' },
    { logo: '/logos/wdex.png', name: 'W-DEX', description: 'Decentralized exchange of the Meta Whale ecosystem' },
    { logo: '/logos/blade.png', name: 'Blade', description: 'Blast-native Dex with real-time vote reward & native multi-call' },
    { logo: '/logos/lynex.svg', name: 'Lynex', description: "Linea's native onchain liquidity marketplace, offering a highly capital-efficient DeFi solution" },
    { logo: '/logos/yaka.svg', name: 'Yaka', description: "The Liquidity Hub On Sei powered by Algebra Integral" },
    { logo: '/logos/thirdfy.jpg', name: 'ThirdFy', description: 'A next-gen Agentic protocol powered by the o(3,3) incentives' },
    { logo: '/logos/tonco.svg', name: 'Tonco', description: 'First V3 DEX on TON with Concentrated Liquidity for better capital efficiency' },
    { logo: '/logos/hypercat.png', name: 'HyperCat', description: 'V4 decentralized exchange on Hyperliquid powered by Algebra' },
    { logo: '/logos/hercules.svg', name: 'Hercules', description: 'A community-first, next-gen DEX for real yield & customizable liquidity infrastructure on Metis' },
    { logo: '/logos/bulla.png', name: 'Bulla', description: 'Native AMM with concentrated liquidity powered by Algebra on Berachain' },
    { logo: '/logos/treble.png', name: 'Treble', description: 'V4 DEX & DeFi Hub on Base powered by Integral: Launch, Swap, Farm, Spend and more' },
    { logo: '/logos/wasabee.svg', name: 'Wasabee', description: 'V4 DEX powered by Algebra. Leveling up meme trading & LP yields on Berachain' },
    { logo: '/logos/morfi.png', name: 'MorFi', description: 'The Native Liquidity and Exchange Layer on MorphLayer' },
    { logo: '/logos/silverswap.jpg', name: 'SilverSwap', description: 'Most versatile DEX & DeFi suite on Fantom' },
    { logo: '/logos/hx.jpg', name: 'HX Finance', description: 'The future of private DeFi on HyperEVM. Efficient swaps now, zero-knowledge privacy on the horizon' },
    { logo: '/logos/zyberswap.svg', name: 'ZyberSwap', description: 'Community driven DEX on Arbitrum and Optimism' },
    { logo: '/logos/swapsicle.svg', name: 'Swapsicle', description: 'A powerful All-In-One DeFi Hub on Telos and Mantle' },
    { logo: '/logos/henjin.jpg', name: 'Henjin', description: 'The native Taiko DEX' },
    { logo: '/logos/synthswap.svg', name: 'SynthSwap', description: 'The leading DEX on Base with concentrated liquidity, built by ZyberSwap' },
    { logo: '/logos/atlantis-on-monad.png', name: 'Atlantis', description: 'The Modular DeFi Hub on Monad' },
    { logo: '/logos/fenix.png', name: 'Fenix DEX', description: 'The Unified Trading and Liquidity Marketplace for Blast' },
    { logo: '/logos/atlantis-on-sonic.jpg', name: 'Atlantis', description: 'The first end-to-end DeFi ecosystem built on Sonic' },
    { logo: '/logos/ocelex.png', name: 'Ocelex', description: 'Most capital-efficient liquidity engine, offering tailored strategies through ALM aggregation, on Zircuit L2' },
    
    // { logo: '/logos/quickswap.svg', name: 'QuickSwap', description: 'QuickSwap is the leading DEX on Polygon with fast & near-zero transaction fees' },
    // { logo: '/logos/lynex.svg', name: 'Lynex', description: "Linea's native on-chain liquidity marketplace, offering a highly capital-efficient DeFi solution" },
    // { logo: '/logos/kim.png', name: 'Kim', description: "The liquidity hub of the Optimism Superchain. One mission: To become the most rewarding place for you to park your DeFi assets" },
    // { logo: '/logos/blade.png', name: 'BladeSwap', description: "Blast native Dex with real-time vote reward & native multi-call" },
    // { logo: '/logos/hercules.svg', name: 'Hercules', description: 'A friendly fork of Camelot coming soon to the Metis Ecosystem' },
    // { logo: '/logos/swapsicle.svg', name: 'Swapsicle', description: 'A powerful All-In-One DeFi Hub on Telos and Mantle' },
    // { logo: '/logos/fenix.svg', name: 'Fenix', description: 'The Unified Trading and Liquidity Marketplace for Blast' },
    // { logo: '/logos/swapr.svg', name: 'Swapr', description: 'Your DeFi power tool. Swap, farm and bridge without worrying about privacy' },
    // { logo: '/logos/silverswap.jpg', name: 'SilverSwap', description: 'Most versatile DEX & DeFi suite on Fantom' },
    // { logo: '/logos/zyberswap.svg', name: 'ZyberSwap', description: 'Community driven DEX on Arbitrum and Optimism' },
    // { logo: '/logos/synthswap.svg', name: 'SynthSwap', description: 'The leading DEX on Base with concentrated liquidity, built by ZyberSwap' },
    // { logo: '/logos/horizon.svg', name: 'Horizon', description: 'HorizonDEX is high performing Concentrated Liquidity DEX on Linea and Base' },
    // { logo: '/logos/henjin.jpg', name: 'Henjin', description: 'The native Taiko DEX' },
    // { logo: '/logos/stellaswap.svg', name: 'StellaSwap', description: 'Hybrid DEX on Moonbeam & DeFi gateway to Polkadot' },
    // { logo: '/logos/yaka.png', name: 'Yaka', description: "Sei's native liquidity engine, drives the eco forward" },
    // { logo: '/logos/fibonacci.jpg', name: 'Fibonacci', description: 'Leading DEX on Form' },
    // { logo: '/logos/thirdfy.jpg', name: 'ThirdFy', description: 'Forget Fees, Just Trade. Experience Unlimited Zero Gas Fee Swaps, RWAs Trading, Launchpad, and more. Gasless is the new standard' },
    // { logo: '/logos/swapx.jpg', name: 'SwapX', description: 'Revolutionary Modular Architecture — premier DEX on Sonic' },
    // { logo: '/logos/grizzly.jpg', name: 'Grizzly Finance', description: 'DeFi and Liquidity hub for strong Beras on Bera chain' },
    // { logo: '/logos/scribe.png', name: 'Scribe DEX', description: 'The quill of decentralized finance, rewriting DeFi on zk realms on Scroll' },
    // { logo: '/logos/ocelex.png', name: 'Ocelex', description: 'Enhancing the DEX experience on Zircuit L2 with the most capital-efficient liquidity engine, offering tailored strategies through ALM aggregation' },
    // { logo: '/logos/circuit.svg', name: 'Circuit', description: 'The first native thesis-driven DEX on Zircuit L2, providing the greatest liquidity efficiency' },
    // { logo: '/logos/supersonic.svg', name: 'SuperSonic', description: 'The Advanced DEX built natively on the Sonic Network, offering futures, launchpad, swaps, and automated liquidity management' },
    // { logo: '/logos/tokan.svg', name: 'Tokan Exchange', description: 'The Native Liquidity and Exchange Layer for Scroll' },
    // { logo: '/logos/honeypot.svg', name: 'Honeypot Finance', description: 'DeFi Hub & PoL Accelerator that unites a fair launchpad and a secure DEX on Bera chain' },
    // { logo: '/logos/molten.jpg', name: 'Molten', description: 'Building the Bitcoin-powered flagship DEX on CoreDAO' },
    // { logo: '/logos/planar.svg', name: 'Planar', description: 'Native DEX and Liquidity Infrastructure Protocol on Blast' },
    // { logo: '/logos/treble.png', name: 'TrebleSwap', description: 'DeFi Hub to Launch, Swap, Farm, Spend and more, on Base' },
    // { logo: '/logos/wdex.png', name: 'W-DEX', description: 'A decentralized AMM-based exchange for ERC-20 tokens, offering secure, low-cost trading with a user-friendly experience' },
]

const EcosystemDEXsPage = () => <EcosystemGrid>
    {dexs.map((dex, idx) => <EcosystemCard key={`dex-card-${dex.name}-${idx}`} {...dex} />)}
</EcosystemGrid>

export default EcosystemDEXsPage;
